import typer
import os
import shutil
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt
from qa_framework.core.logger import get_logger

app = typer.Typer(help="QA Framework CLI Tool")
console = Console()
logger = get_logger(name="cli")

# Template files content
DEFAULT_ENV = """# QA Framework Configuration
BASE_URL=https://example.com
BROWSER=chrome
HEADLESS=false
USE_PLAYWRIGHT=true
LOG_LEVEL=INFO
DB_CONNECTION_STRING=sqlite:///test.db
"""

DEFAULT_CONFTEST = """import pytest
from qa_framework.core.drivers.factory import DriverFactory
from qa_framework.core.config import settings
from qa_framework.core.logger import get_logger

logger = get_logger()

@pytest.fixture(scope="session")
def driver():
    logger.info("Initializing Driver from conftest")
    driver_instance = DriverFactory.get_driver(settings.BROWSER)
    yield driver_instance
    logger.info("Quitting Driver")
    driver_instance.quit()
"""

DEFAULT_TEST = """from qa_framework.core.drivers.base_page import BasePage

def test_example(driver):
    driver.goto("https://www.google.com")
    assert "Google" in driver.title
    print("Test Passed: Navigated to Google")
"""

@app.command()
def init(
    project_name: str = typer.Option(..., prompt=True, help="Name of the test project"),
    directory: str = typer.Option(".", help="Directory to initialize in")
):
    """
    Initialize a new QA project with the recommended structure.
    """
    base_path = Path(directory) / project_name
    
    if base_path.exists():
        if not typer.confirm(f"Directory {base_path} already exists. Overwrite?"):
            console.print("[red]Aborted.[/red]")
            raise typer.Abort()
        shutil.rmtree(base_path)

    console.print(f"[bold green]Creating project: {project_name}...[/bold green]")

    # Define structure
    folders = [
        "tests",
        "tests/ui",
        "tests/api",
        "pages",
        "data",
        "config",
        "utils",
        "reports",
        "reports/allure-results"
    ]

    for folder in folders:
        (base_path / folder).mkdir(parents=True, exist_ok=True)

    # Create files
    (base_path / ".env").write_text(DEFAULT_ENV)
    (base_path / "tests/conftest.py").write_text(DEFAULT_CONFTEST)
    (base_path / "tests/ui/test_demo.py").write_text(DEFAULT_TEST)
    (base_path / "tests/ui/test_demo.py").write_text(DEFAULT_TEST)
    (base_path / "README.md").write_text(f"# {project_name}\n\nGenerated by QA Framework.")
    (base_path / ".gitignore").write_text("__pycache__/\n*.pyc\nreports/\n.env\n.pytest_cache/\n")

    console.print(f"[green]✔ Project initialized at {base_path.absolute()}[/green]")
    console.print("\n[yellow]Next Steps:[/yellow]")
    console.print(f"1. cd {project_name}")
    console.print("2. pip install -r requirements.txt (if applicable)")
    console.print("3. pytest")

if __name__ == "__main__":
    app()
