import typer
import os
import shutil
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt
from qa_framework.core.logger import get_logger

app = typer.Typer(help="QA Framework CLI Tool")
console = Console()
logger = get_logger(name="cli")

# Template files content
DEFAULT_ENV = """# QA Framework Configuration
BASE_URL=https://example.com
BROWSER=chrome
HEADLESS=false
USE_PLAYWRIGHT=true
LOG_LEVEL=INFO
DB_CONNECTION_STRING=sqlite:///test.db
SCREENSHOT_ON_PASS=false
"""

DEFAULT_CONFTEST = '''import pytest
from qa_framework.core.drivers.factory import DriverFactory
from qa_framework.core.config import settings
from qa_framework.core.logger import get_logger

logger = get_logger()

@pytest.fixture(scope="function")
def driver():
    logger.info("Initializing Driver from conftest")
    driver_instance = DriverFactory.get_driver(settings.BROWSER)
    yield driver_instance
    logger.info("Quitting Driver")
    driver_instance.quit()

@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """
    Hook to capture screenshot on failure (or pass if configured).
    """
    outcome = yield
    rep = outcome.get_result()
    
    # We only care about the call phase (executing the test), not setup/teardown
    if rep.when == "call":
        driver = item.funcargs.get('driver')
        if driver:
            from qa_framework.core.listeners.allure_listener import AllureListener
            import os
            
            # Screenshot on Failure
            if rep.failed:
                AllureListener.attach_screenshot(driver, name=f"Failure_{item.name}")
                
            # Screenshot on Pass (if configured)
            elif str(os.getenv("SCREENSHOT_ON_PASS", "false")).lower() == "true":
                AllureListener.attach_screenshot(driver, name=f"Success_{item.name}")
'''

DEFAULT_TEST = """from qa_framework.core.drivers.base_page import BasePage

def test_example(driver):
    driver.goto("https://www.google.com")
    assert "Google" in driver.get_title()
    print("Test Passed: Navigated to Google")
"""

BDD_FEATURE = """Feature: Google Search
  As a web user
  I want to search on Google
  So that I can find information

  Scenario: Search for QA Framework
    Given I am on the Google homepage
    When I search for "QA Framework"
    Then the title should contain "Google"
"""

BDD_STEP_DEFS = """from pytest_bdd import scenario, given, when, then, parsers
from qa_framework.core.drivers.base_page import BasePage

@scenario('../features/search.feature', 'Search for QA Framework')
def test_search():
    pass

@given("I am on the Google homepage")
def open_google(driver):
    driver.goto("https://www.google.com")

@when(parsers.parse('I search for "{text}"'))
def search_google(driver, text):
    # This is a raw interaction for demo, normally use a Page Object
    pass

@then(parsers.parse('the title should contain "{text}"'))
def verify_title(driver, text):
    assert text in driver.get_title()
"""

ROBOT_TEST = """*** Settings ***
Library    QA_Framework_Library

*** Test Cases ***
Example Test
    Open Browser    https://google.com
    Title Should Contain    Google
"""

@app.command()
def init(
    project_name: str = typer.Option(..., prompt=True, help="Name of the test project"),
    directory: str = typer.Option(".", help="Directory to initialize in")
):
    """
    Initialize a new QA project with the recommended structure.
    """
    base_path = Path(directory) / project_name
    
    if base_path.exists():
        if not typer.confirm(f"Directory {base_path} already exists. Overwrite?"):
            console.print("[red]Aborted.[/red]")
            raise typer.Abort()
        shutil.rmtree(base_path)

    # Ask for Project Type
    console.print("\n[bold]Select Project Style:[/bold]")
    console.print("[1] Standard TDD/POM (Recommended)")
    console.print("[2] BDD (Gherkin/Cucumber)")
    console.print("[3] Robot Framework (Keyword Driven)")
    choice = typer.prompt("Enter number", default="1", show_default=True)

    console.print(f"[bold green]Creating project: {project_name}...[/bold green]")

    # Base Folders
    folders = [
        "pages",
        "data",
        "config",
        "utils",
        "reports",
        "reports/allure-results"
    ]
    
    # Conditional Folders
    if choice == "2":
        folders.extend(["tests", "tests/features", "tests/step_defs"])
    elif choice == "3":
        folders.extend(["tests", "tests/robot", "keywords"])
    else:
        folders.extend(["tests", "tests/ui", "tests/api"])

    for folder in folders:
        (base_path / folder).mkdir(parents=True, exist_ok=True)

    # Common Files
    (base_path / ".env").write_text(DEFAULT_ENV)
    (base_path / "tests/conftest.py").write_text(DEFAULT_CONFTEST)
    (base_path / "README.md").write_text(f"# {project_name}\n\nGenerated by QA Framework.")
    (base_path / ".gitignore").write_text("__pycache__/\n*.pyc\nreports/\n.env\n.pytest_cache/\n")

    # Specific Files
    if choice == "2":
        # BDD Setup
        (base_path / "tests/features/search.feature").write_text(BDD_FEATURE)
        (base_path / "tests/step_defs/test_search.py").write_text(BDD_STEP_DEFS)
        console.print("[blue]ℹ️  Created BDD structure: features/ & step_defs/[/blue]")
    elif choice == "3":
        # Robot Setup
        (base_path / "tests/robot/example.robot").write_text(ROBOT_TEST)
        console.print("[blue]ℹ️  Created Robot structure: tests/robot/[/blue]")
    else:
        # Standard Setup
        (base_path / "tests/ui/test_demo.py").write_text(DEFAULT_TEST)

    console.print(f"[green]✔ Project initialized at {base_path.absolute()}[/green]")
    console.print("\n[yellow]Next Steps:[/yellow]")
    console.print(f"1. cd {project_name}")
    console.print("2. pip install -r requirements.txt (if applicable)")
    console.print("3. pytest")

if __name__ == "__main__":
    app()
